---
# Source: helm for kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homework
  labels:
    app: homework
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homework
  template:
    metadata:
      labels:
        app: homework
    spec:
      containers:
        - name: homework
          image: docker.io/phengbunath/homework:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
